services:

  microcks-kafka:
    image: quay.io/strimzi/kafka:0.43.0-kafka-3.8.0
    container_name: microcks-kafka
    depends_on:
      - microcks-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: microcks-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://microcks-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  microcks-async-minion:
    image: quay.io/microcks/microcks-async-minion:1.13.2
    container_name: microcks-async-minion
    depends_on:
      - microcks
      - microcks-kafka
    ports:
      - "8081:8081"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: microcks-kafka:9092
      MICROCKS_URL: http://microcks:8080
